{
	:code=>"App",
	:id=>"88",
	:name=>"Appropriations",
	:type=>"House",
	:address=>{
		:city=>"Atlanta",
		:email=>nil,
		:fax=>"4044632249",
		:phone=>"4044632247",
		:state=>"Ga        ",
		:street=>"245 State Capitol",
		:zip=>"30334     "
	},
	:description=>"The main focus of the committee is the writing of the state’s amended and general fiscal year budgets for Georgia’s state agencies and departments.  The committee also hears legislation that has considerable impact on the state revenue or expenditures.",
	:members=>{
		:committee_member=>[
			{
				:date_vacated=>#<DateTime: 2013-08-26T00:00:00+00:00 ((2456531j,0s,0n),+0s,2299161j)>,
				:member=>{
					:date_vacated=>#<DateTime: 2013-08-26T00:00:00+00:00 ((2456531j,0s,0n),+0s,2299161j)>,
					:district=>{
						:coverage=>nil,
						:post=>nil,
						:id=>"152",
						:type=>"House",
						:number=>"104"
					},
					:district_address=>{
						:city=>"Dacula",
						:email=>nil,
						:fax=>nil,
						:phone=>nil,
						:state=>"GA",
						:street=>"PO Box 893",
						:zip=>"30019     "
					},
					:leg_id=>"1060",
					:name=>{
						:first=>"Donna",
						:last=>"Sheldon",
						:middle=>nil,
						:nickname=>nil},
						:party=>"Republican",
						:id=>"205"
					},
					:role=>"Member",
					:sub_committees=>{
						:sub_committee=>{
							:id=>"12", 
							:name=>"Health"
						}
					}
				}
			},
			{
				:date_vacated=>nil,
				:member=>{
					:date_vacated=>nil,
					:district=>{
						:coverage=>nil,
						:post=>nil,
						:id=>"164",
						:type=>"House",
						:number=>"116"
					},
					:district_address=>{
						:city=>"Auburn", 
						:email=>nil, 
						:fax=>nil, 
						:phone=>nil, 
						:state=>"GA", 
						:street=>nil, 
						:zip=>nil
					}, 
					:leg_id=>"1069",
					:name=>{
						:first=>"Terry", 
						:last=>"England", 
						:middle=>nil, 
						:nickname=>nil
					}, 
					:party=>"Republican", 
					:id=>"98"
				}, 
				:role=>"Chairman", 
				:sub_committees=>nil
			},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"15", :type=>"House", :number=>"13"}, :district_address=>{:city=>"Rome", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"811 Highland Avenue", :zip=>"30161     "}, :leg_id=>"840", :name=>{:first=>"Katie", :last=>"Dempsey", :middle=>"M.", :nickname=>nil}, :party=>"Republican", :id=>"92"}, :role=>"Chairman of Subcommittee", :sub_committees=>{:sub_committee=>{:id=>"14", :name=>"Human Resources"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"8", :type=>"House", :number=>"6"}, :district_address=>{:city=>"Cohutta", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"5043 Village Drive", :zip=>"30710     "}, :leg_id=>"729", :name=>{:first=>"Tom", :last=>"Dickson", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"93"}, :role=>"Chairman of Subcommittee", :sub_committees=>{:sub_committee=>{:id=>"11", :name=>"Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"48", :type=>"House", :number=>"36"}, :district_address=>{:city=>"Powder Springs", :email=>nil, :fax=>"7704372601", :phone=>"7704377536", :state=>"GA", :street=>"5500 Wright Road", :zip=>"30127     "}, :leg_id=>"132", :name=>{:first=>"Earl", :last=>"Ehrhart", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"97"}, :role=>"Chairman of Subcommittee", :sub_committees=>{:sub_committee=>{:id=>"13", :name=>"Higher Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"226", :type=>"House", :number=>"170"}, :district_address=>{:city=>"Nashville", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"8395 Highway 129", :zip=>"31639     "}, :leg_id=>"789", :name=>{:first=>"Penny", :last=>"Houston", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"130"}, :role=>"Chairman of Subcommittee", :sub_committees=>{:sub_committee=>{:id=>"10", :name=>"Economic Development"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"214", :type=>"House", :number=>"158"}, :district_address=>{:city=>"Swainsboro", :email=>nil, :fax=>nil, :phone=>"4782373838", :state=>"GA", :street=>"132 Victory Drive", :zip=>"30401     "}, :leg_id=>"1109", :name=>{:first=>"Butch", :last=>"Parrish", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"183"}, :role=>"Chairman of Subcommittee", :sub_committees=>{:sub_committee=>{:id=>"12", :name=>"Health"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"227", :type=>"House", :number=>"171"}, :district_address=>{:city=>"Camilla", :email=>nil, :fax=>nil, :phone=>"2293363962", :state=>"Ga", :street=>"PO Box 188", :zip=>"31730     "}, :leg_id=>"906", :name=>{:first=>"Jay", :last=>"Powell", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"728"}, :role=>"Chairman of Subcommittee", :sub_committees=>{:sub_committee=>{:id=>"15", :name=>"Public Safety"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"208", :type=>"House", :number=>"152"}, :district_address=>{:city=>"Albany", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"423 Martindale Drive", :zip=>"31721     "}, :leg_id=>"784", :name=>{:first=>"Ed", :last=>"Rynders", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"198"}, :role=>"Chairman of Subcommittee", :sub_committees=>{:sub_committee=>{:id=>"9", :name=>"General Government"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"155", :type=>"House", :number=>"107"}, :district_address=>{:city=>"Lilburn", :email=>nil, :fax=>"7709318839", :phone=>"7709318033", :state=>"GA", :street=>"PO Box 283", :zip=>"30048     "}, :leg_id=>"1062", :name=>{:first=>"David", :last=>"Casas", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"78"}, :role=>"Vice Chairman", :sub_committees=>{:sub_committee=>{:id=>"11", :name=>"Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"192", :type=>"House", :number=>"138"}, :district_address=>{:city=>"Americus", :email=>nil, :fax=>"2299247893", :phone=>"2299247823", :state=>"GA", :street=>"PO Box 824", :zip=>"31709     "}, :leg_id=>"1125", :name=>{:first=>"Mike", :last=>"Cheokas", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"81"}, :role=>"Vice Chairman", :sub_committees=>{:sub_committee=>{:id=>"13", :name=>"Higher Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"194", :type=>"House", :number=>"140"}, :district_address=>{:city=>"Musella", :email=>nil, :fax=>nil, :phone=>"4788364362", :state=>"GA", :street=>"PO Box 10", :zip=>"31066     "}, :leg_id=>"1093", :name=>{:first=>"Robert", :last=>"Dickey", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"791"}, :role=>"Vice Chairman", :sub_committees=>{:sub_committee=>{:id=>"9", :name=>"General Government"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"200", :type=>"House", :number=>"144"}, :district_address=>{:city=>"Dry Branch", :email=>nil, :fax=>"4787559046", :phone=>"4787439901", :state=>"Ga", :street=>"4511 Old Gordon Road", :zip=>"31020     "}, :leg_id=>"1097", :name=>{:first=>"James", :last=>"Epps", :middle=>nil, :nickname=>"Bubber"}, :party=>"Republican", :id=>"733"}, :role=>"Vice Chairman", :sub_committees=>{:sub_committee=>{:id=>"14", :name=>"Human Resources"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"207", :type=>"House", :number=>"151"}, :district_address=>{:city=>"Cuthbert", :email=>nil, :fax=>"2297322973", :phone=>nil, :state=>"GA", :street=>"Route 3, Box 316", :zip=>"39840     "}, :leg_id=>"1103", :name=>{:first=>"Gerald", :last=>"Greene", :middle=>"E", :nickname=>nil}, :party=>"Republican", :id=>"115"}, :role=>"Vice Chairman", :sub_committees=>{:sub_committee=>{:id=>"15", :name=>"Public Safety"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"172", :type=>"House", :number=>"122"}, :district_address=>{:city=>"Evans", :email=>nil, :fax=>"7068638959", :phone=>"7068691953", :state=>"GA", :street=>"4571-A Cox Road", :zip=>"30809     "}, :leg_id=>"1075", :name=>{:first=>"Ben", :last=>"Harbin", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"118"}, :role=>"Vice Chairman", :sub_committees=>{:sub_committee=>{:id=>"12", :name=>"Health"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"216", :type=>"House", :number=>"160"}, :district_address=>{:city=>"Brooklet", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"PO Box 187", :zip=>"30415     "}, :leg_id=>"1111", :name=>{:first=>"Jan", :last=>"Tankersley", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"783"}, :role=>"Vice Chairman", :sub_committees=>{:sub_committee=>{:id=>"10", :name=>"Economic Development"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"231", :type=>"House", :number=>"175"}, :district_address=>{:city=>"Valdosta", :email=>nil, :fax=>"2292458890", :phone=>"2292452733", :state=>"GA", :street=>"PO Box 4930", :zip=>"31604     "}, :leg_id=>"862", :name=>{:first=>"Amy", :last=>"Carter", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"76"}, :role=>"Secretary", :sub_committees=>{:sub_committee=>{:id=>"11", :name=>"Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"137", :type=>"House", :number=>"89"}, :district_address=>{:city=>"Atlanta", :email=>nil, :fax=>"4043783328", :phone=>"4043789434", :state=>"GA", :street=>"1912 Hosea Williams Drive", :zip=>"30317     "}, :leg_id=>"1050", :name=>{:first=>"Stacey", :last=>"Abrams", :middle=>nil, :nickname=>nil}, :party=>"Democrat", :id=>"58"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"9", :name=>"General Government"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"10", :type=>"House", :number=>"8"}, :district_address=>{:city=>"Blairsville", :email=>nil, :fax=>nil, :phone=>"7067813929", :state=>"Ga", :street=>"103 Blue Ridge Street", :zip=>"30512     "}, :leg_id=>"889", :name=>{:first=>"Stephen", :last=>"Allison", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"726"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"9", :name=>"General Government"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"235", :type=>"House", :number=>"179"}, :district_address=>{:city=>"Brunswick", :email=>nil, :fax=>nil, :phone=>"9122655515", :state=>"GA", :street=>"1515 Newcastle Street", :zip=>"31520     "}, :leg_id=>"970", :name=>{:first=>"Alex", :last=>"Atwood", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"788"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"13", :name=>"Higher Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"21", :type=>"House", :number=>"15"}, :district_address=>{:city=>"Cartersville", :email=>nil, :fax=>nil, :phone=>nil, :state=>"Ga", :street=>"208 Rd. #2, S.W.", :zip=>"30120     "}, :leg_id=>"891", :name=>{:first=>"Paul", :last=>"Battles", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"734"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"13", :name=>"Higher Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"230", :type=>"House", :number=>"174"}, :district_address=>{:city=>"Valdosta", :email=>nil, :fax=>"2295591592", :phone=>nil, :state=>"GA", :street=>"5900 Jumping Gully Road", :zip=>"31601     "}, :leg_id=>"792", :name=>{:first=>"Ellis", :last=>"Black", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"66"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"10", :name=>"Economic Development"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"150", :type=>"House", :number=>"102"}, :district_address=>{:city=>"Lawrenceville", :email=>nil, :fax=>nil, :phone=>"6788959064", :state=>"GA", :street=>"PO Box 491355", :zip=>"30049     "}, :leg_id=>"1058", :name=>{:first=>"Buzz", :last=>"Brockway", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"773"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"14", :name=>"Human Resources"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"218", :type=>"House", :number=>"162"}, :district_address=>{:city=>"Garden City", :email=>nil, :fax=>"9129640065", :phone=>"9129662777", :state=>"GA", :street=>"4110 4th Street", :zip=>"31408     "}, :leg_id=>"1113", :name=>{:first=>"Bob", :last=>"Bryant", :middle=>nil, :nickname=>nil}, :party=>"Democrat", :id=>"70"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"9", :name=>"General Government"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"215", :type=>"House", :number=>"159"}, :district_address=>{:city=>"Newington", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"5829 Clyo-Kildare Road", :zip=>"30446     "}, :leg_id=>"1110", :name=>{:first=>"Jon", :last=>"Burns", :middle=>"G.", :nickname=>nil}, :party=>"Republican", :id=>"73"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"13", :name=>"Higher Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"168", :type=>"House", :number=>"120"}, :district_address=>{:city=>"Greensboro", :email=>nil, :fax=>"7064531225", :phone=>"7064531230", :state=>"GA", :street=>"PO Box 839", :zip=>"30642     "}, :leg_id=>"1073", :name=>{:first=>"Mickey", :last=>"Channell", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"80"}, :role=>"Ex-Officio", :sub_committees=>{:sub_committee=>{:id=>"12", :name=>"Health"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"146", :type=>"House", :number=>"98"}, :district_address=>{:city=>"Buford", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"420 South Hill Street", :zip=>"30518     "}, :leg_id=>"954", :name=>{:first=>"Josh", :last=>"Clark", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"772"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"10", :name=>"Economic Development"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"149", :type=>"House", :number=>"101"}, :district_address=>{:city=>"Lawrenceville", :email=>nil, :fax=>nil, :phone=>"7703140456", :state=>"GA", :street=>"252 Regal Drive", :zip=>"30046     "}, :leg_id=>"1057", :name=>{:first=>"Valerie", :last=>"Clark", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"775"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"11", :name=>"Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"145", :type=>"House", :number=>"97"}, :district_address=>{:city=>"Duluth", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"3919 Hillside Drive", :zip=>"30096     "}, :leg_id=>"759", :name=>{:first=>"Brooks", :last=>"Coleman", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"84"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"11", :name=>"Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"63", :type=>"House", :number=>"45"}, :district_address=>{:city=>"Marietta", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"PO Box 681746", :zip=>"30068     "}, :leg_id=>"614", :name=>{:first=>"Matt", :last=>"Dollar", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"94"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"12", :name=>"Health"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"186", :type=>"House", :number=>"132"}, :district_address=>{:city=>"LaGrange", :email=>nil, :fax=>"7068840408", :phone=>nil, :state=>"GA", :street=>"PO Box 1368", :zip=>"30241     "}, :leg_id=>"1085", :name=>{:first=>"Carl", :last=>"Epps", :middle=>"Von", :nickname=>nil}, :party=>"Democrat", :id=>"99"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"10", :name=>"Economic Development"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"54", :type=>"House", :number=>"42"}, :district_address=>{:city=>"Smyrna", :email=>nil, :fax=>nil, :phone=>"7707104087", :state=>"GA", :street=>"PO Box 2523", :zip=>"30081     "}, :leg_id=>"1023", :name=>{:first=>"Stacey", :last=>"Evans", :middle=>nil, :nickname=>nil}, :party=>"Democrat", :id=>"762"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"15", :name=>"Public Safety"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"81", :type=>"House", :number=>"57"}, :district_address=>{:city=>"Atlanta", :email=>nil, :fax=>nil, :phone=>"4046560265", :state=>"GA", :street=>"668 East Pelham Road", :zip=>"30324     "}, :leg_id=>"623", :name=>{:first=>"Pat", :last=>"Gardner", :middle=>nil, :nickname=>nil}, :party=>"Democrat", :id=>"109"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"12", :name=>"Health"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"117", :type=>"House", :number=>"75"}, :district_address=>{:city=>"Jonesboro", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"P.O. Box 216", :zip=>"30236     "}, :leg_id=>"1041", :name=>{:first=>"Mike", :last=>"Glanton", :middle=>nil, :nickname=>nil}, :party=>"Democrat", :id=>"111"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"11", :name=>"Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"52", :type=>"House", :number=>"40"}, :district_address=>{:city=>"Smyrna", :email=>nil, :fax=>"7703190970", :phone=>nil, :state=>"GA", :street=>"2372 Simpson Farm Way", :zip=>"30080     "}, :leg_id=>"1021", :name=>{:first=>"Rich", :last=>"Golick", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"112"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"13", :name=>"Higher Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"30", :type=>"House", :number=>"24"}, :district_address=>{:city=>"Cumming", :email=>nil, :fax=>nil, :phone=>"7708446768", :state=>"GA", :street=>"108 Colony Park DriveSuite 400", :zip=>"30040     "}, :leg_id=>"1009", :name=>{:first=>"Mark", :last=>"Hamilton", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"116"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"9", :name=>"General Government"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"204", :type=>"House", :number=>"148"}, :district_address=>{:city=>"Cordele", :email=>nil, :fax=>nil, :phone=>nil, :state=>"Ga", :street=>"458 Lakeshore Way", :zip=>"31015     "}, :leg_id=>"1100", :name=>{:first=>"Buddy", :last=>"Harden", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"724"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"14", :name=>"Human Resources"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"206", :type=>"House", :number=>"150"}, :district_address=>{:city=>"Dublin", :email=>nil, :fax=>"4782753455", :phone=>nil, :state=>"GA", :street=>"100 Canterbury Road", :zip=>"31021     "}, :leg_id=>"1102", :name=>{:first=>"Matt", :last=>"Hatchett", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"781"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"15", :name=>"Public Safety"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"132", :type=>"House", :number=>"86"}, :district_address=>{:city=>"Stone Mountain", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"4140 Creek Stone Court", :zip=>"30083     "}, :leg_id=>"1048", :name=>{:first=>"Michele", :last=>"Henson", :middle=>nil, :nickname=>nil}, :party=>"Democrat", :id=>"124"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"14", :name=>"Human Resources"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"103", :type=>"House", :number=>"68"}, :district_address=>{:city=>"Carrollton", :email=>nil, :fax=>nil, :phone=>"4042851445", :state=>"GA", :street=>"3443 Hog Liver Rd.", :zip=>"30117     "}, :leg_id=>"988", :name=>{:first=>"Dustin", :last=>"Hightower", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"800"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"15", :name=>"Public Safety"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"28", :type=>"House", :number=>"22"}, :district_address=>{:city=>"Canton", :email=>nil, :fax=>"7703452394", :phone=>"6784937257", :state=>"GA", :street=>"145 Mountain Brook Drive", :zip=>"30115     "}, :leg_id=>"1007", :name=>{:first=>"Calvin", :last=>"Hill", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"125"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"14", :name=>"Human Resources"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"217", :type=>"House", :number=>"161"}, :district_address=>{:city=>"Rincon", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"2440 Rincon-Stillwell Rd.", :zip=>"31326     "}, :leg_id=>"1112", :name=>{:first=>"Bill", :last=>"Hitchens", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"823"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"15", :name=>"Public Safety"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"190", :type=>"House", :number=>"136"}, :district_address=>{:city=>"Columbus", :email=>nil, :fax=>"7066875582", :phone=>"7066874327", :state=>"GA", :street=>"PO Box 6342", :zip=>"319176342 "}, :leg_id=>"1089", :name=>{:first=>"Carolyn", :last=>"Hugley", :middle=>nil, :nickname=>nil}, :party=>"Democrat", :id=>"133"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"12", :name=>"Health"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"13", :type=>"House", :number=>"11"}, :district_address=>{:city=>"Jasper", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"89 Apple Valley Farm Lane", :zip=>"30143     "}, :leg_id=>"1002", :name=>{:first=>"Rick", :last=>"Jasperse", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"755"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"11", :name=>"Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"65", :type=>"House", :number=>"47"}, :district_address=>{:city=>"Milton", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"12850 Highway 9Suite 600-356", :zip=>"30004     "}, :leg_id=>"1027", :name=>{:first=>"Jan", :last=>"Jones", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"142"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"11", :name=>"Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"75", :type=>"House", :number=>"53"}, :district_address=>{:city=>"Atlanta", :email=>nil, :fax=>nil, :phone=>nil, :state=>nil, :street=>nil, :zip=>nil}, :leg_id=>"1030", :name=>{:first=>"Sheila", :last=>"Jones", :middle=>nil, :nickname=>nil}, :party=>"Democrat", :id=>"143"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"13", :name=>"Higher Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"83", :type=>"House", :number=>"59"}, :district_address=>{:city=>"Atlanta", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"504 Hill Street", :zip=>"30312     "}, :leg_id=>"846", :name=>{:first=>"Margaret", :last=>"Kaiser", :middle=>"D.", :nickname=>nil}, :party=>"Democrat", :id=>"145"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"11", :name=>"Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"76", :type=>"House", :number=>"54"}, :district_address=>{:city=>"Atlanta", :email=>nil, :fax=>nil, :phone=>"4042641500", :state=>"GA", :street=>"1150 Angelo Court", :zip=>"30319     "}, :leg_id=>"620", :name=>{:first=>"Edward", :last=>"Lindsey", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"154"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"11", :name=>"Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"71", :type=>"House", :number=>"49"}, :district_address=>{:city=>"Alpharetta", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"11770 Haynes Bridge RoadSuite 205-544", :zip=>"30004     "}, :leg_id=>"1028", :name=>{:first=>"Charles", :last=>"Martin", :middle=>"E.", :nickname=>"Chuck"}, :party=>"Republican", :id=>"164"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"9", :name=>"General Government"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"23", :type=>"House", :number=>"17"}, :district_address=>{:city=>"Dallas", :email=>nil, :fax=>nil, :phone=>"7703865420", :state=>"GA", :street=>"716 Graham Road", :zip=>"30132     "}, :leg_id=>"599", :name=>{:first=>"Howard", :last=>"Maxwell", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"165"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"11", :name=>"Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"126", :type=>"House", :number=>"84"}, :district_address=>{:city=>"Decatur", :email=>nil, :fax=>nil, :phone=>nil, :state=>nil, :street=>nil, :zip=>nil}, :leg_id=>"1046", :name=>{:first=>"Rahn", :last=>"Mayo", :middle=>nil, :nickname=>nil}, :party=>"Democrat", :id=>"730"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"10", :name=>"Economic Development"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"51", :type=>"House", :number=>"39"}, :district_address=>{:city=>"Austell", :email=>nil, :fax=>"7709486447", :phone=>nil, :state=>"GA", :street=>"6570 Brandemere Way", :zip=>"30168     "}, :leg_id=>"742", :name=>{:first=>"Alisha", :last=>"Morgan", :middle=>"Thomas", :nickname=>nil}, :party=>"Democrat", :id=>"173"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"10", :name=>"Economic Development"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"212", :type=>"House", :number=>"156"}, :district_address=>{:city=>"Vidalia", :email=>nil, :fax=>nil, :phone=>"9125381062", :state=>"GA", :street=>"PO Box 1749", :zip=>"30475     "}, :leg_id=>"1107", :name=>{:first=>"Greg", :last=>"Morris", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"174"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"14", :name=>"Human Resources"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"2", :type=>"House", :number=>"2"}, :district_address=>{:city=>"LaFayette", :email=>nil, :fax=>"7068662237", :phone=>"4232986217", :state=>"GA", :street=>"PO Box 645", :zip=>"30728     "}, :leg_id=>"1000", :name=>{:first=>"Jay", :last=>"Neal", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"178"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"15", :name=>"Public Safety"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"234", :type=>"House", :number=>"178"}, :district_address=>{:city=>"Blackshear", :email=>nil, :fax=>nil, :phone=>"9128076190", :state=>"GA", :street=>"P.O. Box 1174", :zip=>"31516     "}, :leg_id=>"973", :name=>{:first=>"Chad", :last=>"Nimmer", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"790"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"10", :name=>"Economic Development"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"104", :type=>"House", :number=>"69"}, :district_address=>{:city=>"LaGrange", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"PO Box 991", :zip=>"30241     "}, :leg_id=>"847", :name=>{:first=>"Randy", :last=>"Nix", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"179"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"13", :name=>"Higher Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"124", :type=>"House", :number=>"82"}, :district_address=>{:city=>"Decatur", :email=>nil, :fax=>"4043770486", :phone=>"4043770485", :state=>"GA", :street=>"150 East Ponce de Leon Avenue, Suite 230", :zip=>"30030     "}, :leg_id=>"1044", :name=>{:first=>"Mary", :last=>"Oliver", :middle=>"Margaret", :nickname=>"Mary Margaret"}, :party=>"Democrat", :id=>"181"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"14", :name=>"Human Resources"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"62", :type=>"House", :number=>"44"}, :district_address=>{:city=>"Marietta", :email=>nil, :fax=>nil, :phone=>"7709774426", :state=>"GA", :street=>"3167 Sycamore Lane", :zip=>"30066     "}, :leg_id=>"1025", :name=>{:first=>"Don", :last=>"Parsons", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"184"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"9", :name=>"General Government"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"195", :type=>"House", :number=>"141"}, :district_address=>{:city=>"Macon", :email=>nil, :fax=>nil, :phone=>"4784745633", :state=>"GA", :street=>"103 Colony Court", :zip=>"31210     "}, :leg_id=>"1094", :name=>{:first=>"Allen", :last=>"Peake", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"185"}, :role=>"Ex-Officio", :sub_committees=>{:sub_committee=>{:id=>"10", :name=>"Economic Development"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"38", :type=>"House", :number=>"32"}, :district_address=>{:city=>"Hartwell", :email=>nil, :fax=>nil, :phone=>"7063764422", :state=>"GA", :street=>"3059 Ridge Road", :zip=>"30643     "}, :leg_id=>"1016", :name=>{:first=>"Alan", :last=>"Powell", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"187"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"15", :name=>"Public Safety"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"205", :type=>"House", :number=>"149"}, :district_address=>{:city=>"Eastman", :email=>nil, :fax=>"4783745114", :phone=>"4783744316", :state=>"GA", :street=>"PO Box 459", :zip=>"31023     "}, :leg_id=>"1101", :name=>{:first=>"Jimmy", :last=>"Pruett", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"188"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"9", :name=>"General Government"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"114", :type=>"House", :number=>"72"}, :district_address=>{:city=>"Peachtree City", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"P.O. Box 2325", :zip=>"30269     "}, :leg_id=>"876", :name=>{:first=>"Matt", :last=>"Ramsey", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"190"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"15", :name=>"Public Safety"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"143", :type=>"House", :number=>"95"}, :district_address=>{:city=>"Norcross", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"4151 Blue Iris Hollow", :zip=>"30092     "}, :leg_id=>"1056", :name=>{:first=>"Tom", :last=>"Rice", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"194"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"13", :name=>"Higher Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"211", :type=>"House", :number=>"155"}, :district_address=>{:city=>"Ocilla", :email=>nil, :fax=>"2294680840", :phone=>"2294255404", :state=>"GA", :street=>"767 Brushy Creek Road", :zip=>"31774     "}, :leg_id=>"1106", :name=>{:first=>"Jay", :last=>"Roberts", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"195"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"10", :name=>"Economic Development"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"35", :type=>"House", :number=>"29"}, :district_address=>{:city=>"Gainesville", :email=>nil, :fax=>nil, :phone=>"7703082381", :state=>"GA", :street=>"PO Box 639", :zip=>"30503     "}, :leg_id=>"1014", :name=>{:first=>"Carl", :last=>"Rogers", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"196"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"13", :name=>"Higher Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"47", :type=>"House", :number=>"35"}, :district_address=>{:city=>"Acworth", :email=>nil, :fax=>nil, :phone=>"4046308452", :state=>"GA", :street=>"1555 Boxwood Trace", :zip=>"30102     "}, :leg_id=>"609", :name=>{:first=>"Ed", :last=>"Setzler", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"203"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"14", :name=>"Human Resources"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"173", :type=>"House", :number=>"123"}, :district_address=>{:city=>"Augusta", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"10 Retreat Road", :zip=>"30909     "}, :leg_id=>"1076", :name=>{:first=>"Barbara", :last=>"Sims", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"207"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"12", :name=>"Health"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"107", :type=>"House", :number=>"70"}, :district_address=>{:city=>"Newnan", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"Eight Evergreen Drive", :zip=>"30263     "}, :leg_id=>"632", :name=>{:first=>"Lynn", :last=>"Smith", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"212"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"9", :name=>"General Government"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"188", :type=>"House", :number=>"134"}, :district_address=>{:city=>"Columbus", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"PO Box 2122", :zip=>"31902-2122"}, :leg_id=>"1087", :name=>{:first=>"Richard", :last=>"Smith", :middle=>"H.", :nickname=>nil}, :party=>"Republican", :id=>"213"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"13", :name=>"Higher Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"189", :type=>"House", :number=>"135"}, :district_address=>{:city=>"Columbus", :email=>nil, :fax=>"7066492479", :phone=>"7066492243", :state=>"GA", :street=>"PO Box 181", :zip=>"319020120 "}, :leg_id=>"1088", :name=>{:first=>"Calvin", :last=>"Smyre", :middle=>nil, :nickname=>nil}, :party=>"Democrat", :id=>"216"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"13", :name=>"Higher Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"220", :type=>"House", :number=>"164"}, :district_address=>{:city=>"Savannah", :email=>nil, :fax=>"9129649699", :phone=>"9125961998", :state=>"GA", :street=>"45 Cove Drive", :zip=>"31419     "}, :leg_id=>"686", :name=>{:first=>"Ron", :last=>"Stephens", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"219"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"12", :name=>"Health"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"229", :type=>"House", :number=>"173"}, :district_address=>{:city=>"Thomasville", :email=>nil, :fax=>"2292259945", :phone=>"2292259943", :state=>"GA", :street=>"PO Box 6580", :zip=>"31758     "}, :leg_id=>"968", :name=>{:first=>"Darlene", :last=>"Taylor", :middle=>"K.", :nickname=>nil}, :party=>"Republican", :id=>"786"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"12", :name=>"Health"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"222", :type=>"House", :number=>"166"}, :district_address=>{:city=>"Savannah", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"1326 Eisenhower Drive #2", :zip=>"31406     "}, :leg_id=>"1115", :name=>{:first=>"Ben", :last=>"Watson", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"784"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"12", :name=>"Health"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"3", :type=>"House", :number=>"3"}, :district_address=>{:city=>"Ringgold", :email=>nil, :fax=>nil, :phone=>nil, :state=>"Ga", :street=>"PO Box 1459", :zip=>"30736     "}, :leg_id=>"888", :name=>{:first=>"Tom", :last=>"Weldon", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"732"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"15", :name=>"Public Safety"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"73", :type=>"House", :number=>"51"}, :district_address=>{:city=>"Sandy Springs", :email=>nil, :fax=>"7704817111", :phone=>"7704817110", :state=>"GA", :street=>"755 River Gate Drive", :zip=>"30350     "}, :leg_id=>"1029", :name=>{:first=>"Wendell", :last=>"Willard", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"229"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"15", :name=>"Public Safety"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"167", :type=>"House", :number=>"119"}, :district_address=>{:city=>"Watkinsville", :email=>nil, :fax=>nil, :phone=>nil, :state=>"GA", :street=>"P.O. Box 1365", :zip=>"30677     "}, :leg_id=>"1072", :name=>{:first=>"Chuck", :last=>"Williams", :middle=>nil, :nickname=>nil}, :party=>"Republican", :id=>"792"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"13", :name=>"Higher Education"}}},
			{:date_vacated=>nil, :member=>{:date_vacated=>nil, :district=>{:coverage=>nil, :post=>nil, :id=>"115", :type=>"House", :number=>"73"}, :district_address=>{:city=>"Griffin", :email=>nil, :fax=>"7704127166", :phone=>"7702271474", :state=>"GA", :street=>"961 Birdie Road", :zip=>"30223     "}, :leg_id=>"635", :name=>{:first=>"John", :last=>"Yates", :middle=>"P", :nickname=>nil}, :party=>"Republican", :id=>"235"}, :role=>"Member", :sub_committees=>{:sub_committee=>{:id=>"13", :name=>"Higher Education"}}}
		]
	},
	:session=>{
		:is_default=>true,
		:id=>"23",
		:description=>"2013-2014 Regular Session",
		:library=>"http://www.legis.ga.gov/Legislation/20132014/"
	},
	:session_contexts=>{
		:session=>[
			{:is_default=>true, :id=>"23", :description=>"2013-2014 Regular Session", :library=>"http://www.legis.ga.gov/Legislation/20132014/"},
			{:is_default=>false, :id=>"21", :description=>"2011-2012 Regular Session", :library=>"http://www.legis.ga.gov/Legislation/20112012/"},
			{:is_default=>false, :id=>"22", :description=>"2011 Special Session", :library=>"http://www.legis.ga.gov/Legislation/2011EX1/"},
			{:is_default=>false, :id=>"20", :description=>"2009-2010 Regular Session", :library=>"http://www.legis.ga.gov/Legislation/20092010/"},
			{:is_default=>false, :id=>"18", :description=>"2007-2008 Regular Session", :library=>"http://www.legis.ga.gov/Legislation/20072008/"},
			{:is_default=>false, :id=>"14", :description=>"2005-2006 Regular Session", :library=>"http://www.legis.ga.gov/Legislation/20052006/"},
			{:is_default=>false, :id=>"15", :description=>"2005 Special Session", :library=>"http://www.legis.ga.gov/Legislation/2005EX1/"},
			{:is_default=>false, :id=>"13", :description=>"2004 Special Session", :library=>"http://www.legis.ga.gov/Legislation/2004EX1/"},
			{:is_default=>false, :id=>"11", :description=>"2003-2004 Regular Session", :library=>"http://www.legis.ga.gov/Legislation/20032004/"},
			{:is_default=>false, :id=>"1", :description=>"2001-2002 Regular Session", :library=>"http://www.legis.ga.gov/Legislation/20012002/"},
			{:is_default=>false, :id=>"7", :description=>"2001 2nd Special Session", :library=>"http://www.legis.ga.gov/Legislation/2001EX2/"},
			{:is_default=>false, :id=>"6", :description=>"2001 1st Special Session", :library=>"http://www.legis.ga.gov/Legislation/2001EX1/"}
		]
	},
	:staff=>"<strong>Staff:</strong><a href=\"mailto:emily.pattillo@house.ga.gov\"><br />Emily Pattillo</a> - Administrative Assistant<br /><br /><a href=\"mailto:sheila.raney@house.ga.gov\">Sheila Raney</a> - Administrative Assistant<br /><br /><a href=\"mailto:misty.walker@house.ga.gov\">Misty Walker</a> - Administrative Assistant",
	:sub_committees=>{
		:sub_committee=>[
			{:id=>"14", :name=>"Human Resources"},
			{:id=>"11", :name=>"Education"},
			{:id=>"13", :name=>"Higher Education"},
			{:id=>"10", :name=>"Economic Development"},
			{:id=>"12", :name=>"Health"},
			{:id=>"15", :name=>"Public Safety"},
			{:id=>"9", :name=>"General Government"}
		]
	},
	:"@xmlns:a"=>"http://www.legis.ga.gov/2009/01/01/data/",
	:"@xmlns:i"=>"http://www.w3.org/2001/XMLSchema-instance"
} 